# Generated by Django 3.0.6 on 2020-05-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_disc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_fdisc', models.TextField()),
                ('project_github_link', models.CharField(max_length=10000)),
                ('project_deployed_link', models.CharField(max_length=10000)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='favourite.Projects')),
            ],
        ),
    ]
