# Generated by Django 3.0.6 on 2020-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_deployed_link',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github_link',
            field=models.URLField(max_length=10000),
        ),
    ]
