# Generated by Django 3.0.6 on 2020-06-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_profile',
        ),
    ]
