# Generated by Django 3.0.6 on 2020-06-13 10:27

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_auto_20200613_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_fdisc', models.TextField()),
                ('project_github_link', models.URLField(max_length=1000000)),
                ('project_deployed_link', models.URLField(max_length=1000000)),
                ('project_images', cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_disc',
            new_name='project_idea',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_front_image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='project_disc',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favourite.Projects'),
        ),
    ]
