# Generated by Django 3.0.6 on 2020-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0003_auto_20200613_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_disc',
            name='project_deployed_link',
        ),
        migrations.RemoveField(
            model_name='project_disc',
            name='project_fdisc',
        ),
        migrations.RemoveField(
            model_name='project_disc',
            name='project_github_link',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_deployed_link',
            field=models.URLField(default='deployed link', max_length=1000000),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_github_link',
            field=models.URLField(default='github link', max_length=1000000),
        ),
    ]
