# Generated by Django 3.0.6 on 2020-06-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0005_project_disc_project_dname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_disc',
            name='project_dname',
        ),
    ]
